### ISSUE TITLE
Empty poll

### ISSUE THREAD

**Issue by Galixte** [Wolfsblvt/advancedpolls#101]
Hi @javiexin,

since your last commits, when i edit a topic a poll appears but i haven’t added any poll on this topic, only edit the text of my topic (first post).

**Comment by javiexin** [comment]
This is a "half baked" change, you should not use this just yet :)  But it is good that you did, uncovered this bug.  Thanks for reporting, this will help me debug.
Have you seen the new posting page?  Does it look better?  Facilitates usability?

**Comment by javiexin** [comment]
Fixed.

**Comment by Galixte** [comment]
Thanks !
