### ISSUE TITLE
language/ru/permissions_advancedpolls.php

### ISSUE THREAD

**Issue by edualla** [Wolfsblvt/advancedpolls#11]
<?php
/**
 * 
 * Advanced Polls [Русский]
 * 
 * @copyright (c) 2015 Wolfsblvt ( www.pinkes-forum.de )
 * @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
 * @author Clemens Husung (Wolfsblvt)
 */

if (!defined('IN_PHPBB'))
{
	exit;
}

if (empty($lang) || !is_array($lang))
{
	$lang = array();
}

// DEVELOPERS PLEASE NOTE
//
// All language files should use UTF-8 as their encoding and the files must not contain a BOM.
//
// Placeholders can now contain order information, e.g. instead of
// 'Page %s of %s' you can (and should) write 'Page %1$s of %2$s', this allows
// translators to re-order the output of data while ensuring it remains correct
//
// You do not need this where single placeholders are used, e.g. 'Message %d' is fine
// equally where a string contains only two placeholders which are used to wrap text
// in a url you again do not need to specify an order e.g., 'Click %sHERE%s' is fine

/**
*	EXTENSION-DEVELOPERS PLEASE NOTE
*
*	You are able to put your permission sets into your extension.
*	The permissions logic should be added via the 'core.permissions' event.
*	You can easily add new permission categories, types and permissions, by
*	simply merging them into the respective arrays.
*	The respective language strings should be added into a language file, that
*	start with 'permissions_', so they are automatically loaded within the ACP.
*/

// User Permissions
$lang = array_merge($lang, array(
	'ACL_U_SEE_VOTERS'			=> 'Может видеть пользователей, которые проголосовали, если включено',
));

**Comment by Wolfsblvt** [comment]
Related to #9

**Comment by edualla** [comment]
Danke für die Hinzufügung der Datei für russische Sprache. 
PS: Eine Frage: Kann ich beim nächsten mal die Sprachübersetzungen selber hinzufügen? 
Wenn ja, wie? 
Danke im Voraus. 
Ed

**Comment by Wolfsblvt** [comment]
Hallo @edualla, danke dir für deine Hilfe hier (:
Du kannst es selbst machen, indem du einen Pull Request über GitHub startest. Falls du nicht weißt, wie man so etwas macht, kann ich dir das gerne erklären. Es ist auf jeden Fall gar nicht so schwer.
Du musst quasi lediglich dieses Repository hier "forken" (das kann man oben bei den Buttons machen), und dann einen neuen Ordner für deine Sprache anlegen. Dann sagst du von deinem Fork aus, dass du deine Änderungen in meine Extension einfügen möchtest.

**Comment by edualla** [comment]
Ok, Clemens, jetzt alles klar. 
Vielen Dank für Deine Erklärung. 
Ein schönes Wochenende!
