### ISSUE TITLE
Anyone maintaining this extension?

### ISSUE THREAD

**Issue by jasoloz** [Wolfsblvt/advancedpolls#121]
The topic about this extension in phpBB forum (https://www.phpbb.com/community/viewtopic.php?f=501&t=2326116) was marked as Abandoned in December because of inactivity of the extension author (actually @javiexin died last October). On the other hand, the other author, @Wolfsblvt, is missing. Last active session of @Wolfsblvt in phpBB forum was in October. I have sent an email to @Wolfsblvt through the forum but no answer. I am interested in continuing this project, so I need to know if my future pulls will be accepted or it is better to forget the master branch and to fork a new and independent version of this extension.

**Comment by 3D-I** [comment]
I replied at phpBB com
https://www.phpbb.com/community/viewtopic.php?p=14938226#p14938226
