### ISSUE TITLE
Improper message after poll ended

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#21]
After a poll has ended, the message "Please note that if you vote, your vote will be visible." should not show up any longer.  In fact, the message should only be shown if the user is (still) able to cast a vote (so, if the poll does not allow vote changes and the user has voted, this should not show either, even if the poll has not ended).

**Comment by javiexin** [comment]
Fix available... waiting to know how to create a separate pull request.
Easier fix in the "new" event.

**Comment by Wolfsblvt** [comment]
Do you have also done the fix in js code? I am not quite sure if this notice will be removed there.

**Comment by javiexin** [comment]
Sorry, not possible to fix in your version (without JS at least), you have no information on the status of the poll, whether you can vote or not (S_CAN_VOTE value not available).  Fix is ok for the version based on the new event, just pushed it up, including this fix.  Works fine without touching JS, but may not work if after a vote you loose the possibility to vote (then, comment should be removed).

**Comment by Wolfsblvt** [comment]
I am not quite sure what you mean *confused*

**Comment by javiexin** [comment]
To fix this issue, there is a need to check $s_can_vote. But this is only available in the template variable S_CAN_VOTE, and there is no way to access it through the published interface. Unless you find an alternative via JS, like checking if the "vote" button is visible, I think we are stuck.
With the new (hopefully in 3.1.4) event, this is simple, and already coded in my branch, that anyway relies on that event. Works fine, except when you vote (via ajax), that the message is still available until page is refreshed.
Clearer now?

**Comment by Wolfsblvt** [comment]
If it is fixed in 3.1.4 by your code, then lets keep it. This extension isn't even fully released, so we just take 3.1.4 as the minimum version (:

So the only thing is ajax vote.
And that can be fixed. So I will do that after merging your things later.

**Comment by javiexin** [comment]
Question: should we allow "incremental voting", or provide an option (either ACP global or per poll?).
What I mean by incremental voting is in polls where you may vote for more than 1 option (or scoring polls), you may vote now for one option, then later for another one.  This is currently forbidden, but I think this is limiting, and definitely, for scoring polls, should be adjusted.
It affects this issue as the label should appear only if you are able to vote, but depending on this question, the time is different, and the way to calculate it as well.

**Comment by Wolfsblvt** [comment]
If "Allow vote change" it should be possible at the moment. It is even in default phpBB.
If vote change is not allowed, you shouldn't be able to change it, so also not add another vote.
"Don't allow vote change" means that you vote once, and can't change it.
And I think we should not modify that logic.

**Comment by javiexin** [comment]
The question is for "vote changes not allowed" cases, with allowed changes this is not an issue.
I disagree.  If you add a vote, you are not changing anything, you are adding extra votes, not modifying what you already did.
An example use case: you can use scoring polls for "requests" or "orders".  For example, "do you want a T-shirt with the forum logo? what size?" could be implemented as a scoring poll, without vote changes, but with incremental votes.
At a minimum, we should provide an ACP global option.

**Comment by Wolfsblvt** [comment]
Of course. A "vote" is also a combination of different options you have voted for, Also if you choose different scores, this count as a vote. Changing the scores or voting for another options means changing your current vote for this poll.
"vote changes not allowed" means you vote once, and cannot change again. Otherwise it speaks

But if you are happy with it, you can add an ACP global option for it, but please with default value to false :P

**Comment by javiexin** [comment]
Fixed and committed.
