### ISSUE TITLE
Default options not used when editing an existing topic without a poll

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/advancedpolls#23]
"Maybe I found a small bug, but it could be feature. When I (as admin) edit already existing topic to add poll it seems that default options (from ACP) are not mirrored in the poll editor (they are unticked). When I create new topic, everything is OK."

Reported here: https://www.phpbb.com/community/viewtopic.php?p=14033241#p14033241

**Comment by javiexin** [comment]
I have a fix for this, will send later when I am at home.

**Comment by Wolfsblvt** [comment]
Yeah, a small change needed :D
You should submit an additional pull request for that (from a different branch of your fork for example).
If you add "Fixes #23" in the commit description, this bug will automatically be closed on merge.

**Comment by javiexin** [comment]
Ok, I have the changes in a separate branch of my local GIT, but don't know how to make it available to you, creating a different branch.
I have fixes for your other two issues/bugs as well... waiting for this to upload them...

**Comment by Wolfsblvt** [comment]
If you have them already in a seperate branch, you just have to push the branch to your repository. For example with `git push origin branchname` where "branchname" is your branch name :P
When you have pushed the branch, easiest way for a pull request is to to github online, select the branch and then a lightyellow box with suggestion to do a pull request should already appear.

**Comment by javiexin** [comment]
Done :) thanks a lot.  Fixes for #18 and #23 available in the pull request.

2015-04-08 17:34 GMT+02:00 Wolfsblvt <notifications@github.com>:
