### ISSUE TITLE
Functionality to let people decide to be excluded from show voters

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/advancedpolls#26]
There may be users, who don't want their vote to be displayed for all others. They should have the chance to exclude their votes.

It needs to be considered to als add an option to deactivate this choice for specific polls, and maybe even a switch in ACP for admin to decide if the voters that don't want their vote to be shown should be fully hidden or listed with names below the votes.

**Comment by Wolfsblvt** [comment]
We should postpone this at the moment. All other things are more important.
If we have a stable version of this extension, we may can think about this again.

**Comment by javiexin** [comment]
Fully agree, this is tricky and may be delayed.  We may ask others if this would be a useful option.
