### ISSUE TITLE
Remove of old workaround for missing event

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/advancedpolls#29]

**Comment by javiexin** [comment]
When working on this, I have spotted what might be an error in your code for posting_poll_body.html, here: https://github.com/phpbb/phpbb/pull/3517

In case both S_POLL_DELETE and S_SHOW_POLL_BOX are true, the POLL_DELETE block is duplicated.

Line 49 should be:
	

Problem is this has already been merged into 3.1.4-RC1 (I think!).

**Comment by Wolfsblvt** [comment]
You are right. I would do it easer though and just move the  block outside of the S_SHOW_POLL_BOX statement and delete the if block down there. This way we have also got rid of duplicated code, **and** the event is below the poll_delete option in both cases, wich is more consistent.

Will you do a pull request to phpBB for that or should I do it?

**Comment by javiexin** [comment]
I think it is better that you do...
I agree with your proposed change, only it is more intrusive with the original code, and it may be more difficult to approve, I don't know. But I prefer it as well.
