### ISSUE TITLE
Scoring polls

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#30]
Add functionality to allow for polls to attach different votes to several options.  For example, give 10 points, to at most 4 options, with at most 4 points per option, out of a total of 15 options...
This will allow "contest" votings.

**Comment by javiexin** [comment]
Question: how can I block or modify a phpbb AJAX request? Reason is that the current viewtopic accounts for votes and sends the response and a refresh via AJAX before there is any core event, so I cannot intercept and modify the way votes are accounted for, and therefore I cannot implement scoring polls properly.  I would not like to completely disable ajax... (by the way, how would you do that for this specific case?).  Thanks a lot...

**Comment by Wolfsblvt** [comment]
completely disable ajax? I am not quite sure if this really is a good idea. I mean ajax is needed is for a lot of stuff, right?

Blocking an ajax request is difficult. You can stop it on server side of course, but other way...
You can replace callbacks easily (see [here](https://github.com/Wolfsblvt/advancedpolls/blob/master/styles/prosilver/template/js/onload.js#L11-L20)), but the request, once executed in the code, it will be executed.
You will have to find a different way.

**Comment by javiexin** [comment]
Ok, if you can replace or add to existing callbacks, I guess that will be ok.  My problem is that the php code that is executed on the server side is not right for scoring polls, and there is no event there...

But if the existing callback may be replaced, then it should work.  I will have to talk to you to have it behave properly :)

**Comment by javiexin** [comment]
The code in https://github.com/rxu/phpbb3/blob/ticket/13745/phpBB/viewtopic.php#L807-921 is the one that is executed in an ajax call (as far as I see) without reaching the event, and therefore, without the option to intercept it, unless this is done via JS.  Do you think this can be done?
Thanks!

**Comment by Wolfsblvt** [comment]
The problem is you shouldn't really change whole core parts, that's a problem for many things. And that is a problem here too.
Is there no possibility to build up your wished feature on top of that, without changing how the core works?

**Comment by javiexin** [comment]
I don't mean to change this code, what I want is to modify the behavior of this part.  For example, to include scoring, I need to record (in the votes table) how many points are assigned, vs just noting who voted what, and that needs to be done there; I can add extra votes after this, but not if this "ends" the execution by forcing a refresh... (line 919). So the question really is how to stop that refresh, or execute code before or after it but definitely before the user sees the browser again...  Did I make sense?

**Comment by Wolfsblvt** [comment]
Can't you get your data from ajax request at `core.viewtopic_assign_template_vars_before`?
Otherwise you need a new event, yes.

**Comment by javiexin** [comment]
Yes, you could do it there... but would mean duplicating some code.  The ideal place for the new event would be L806, just before  if ($update && $s_can_vote)
Given that we have to wait for 3.1.5 anyway, I may ask for this one.

**Comment by Wolfsblvt** [comment]
Code duplication is not so bad when it is just executed once. (Wich it is when you return json there)
The code you have duplicated will just run when you are sure that it is needed and that you will quit after that. For example if you add a new parameter to the vote form when it is a scoring vote.

Otherwise you can request a new event, yes.

**Comment by javiexin** [comment]
Finally, there are going to be two separate events, the second one being in the position I suggested. So, I will be relying on both of those events, that will be available in 3.1.5.  The viewtopic code has changed again.  The only minor issue is that the first event added has been renamed, and the new one has the name of the old one, so there will have to be some minor changes to the current pushed version of AP (just change in listener for the new name of the event we are using).

**Comment by javiexin** [comment]
New code for viewtopic is here:
https://github.com/rxu/phpbb3/commit/615e5c107672b17f5a00f4547a8537e9a5790f9b
