### ISSUE TITLE
Ability for admins/mods to see all voters (permission based)

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#31]
Add an admin/mod level permission to see all voters of a poll, regardless of specific poll settings.

**Comment by Wolfsblvt** [comment]
Note: This should not go for timed hidden polls. Even admins should not see them.

**Comment by javiexin** [comment]
This could be implemented either as a quickmod action or as a poll action (button like the post edit, post report, etc.), what do you think/prefer?

**Comment by Wolfsblvt** [comment]
I don't think why another option is needed here. That just overcomplicates everything.
My first thought here was just show the voters on every poll, if you have the permission. (unless the votes are hidden)

**Comment by javiexin** [comment]
I don't think showing the voters upfront is the right thing for this case. It is something to be done "on demand", when the admin/mod needs that information. The question is how to ask for it, either as a quickmod action or as a button on the top-right of the poll...

**Comment by Wolfsblvt** [comment]
Okay, maybe you are right.
We should do a button shown for people with that persmission, handle that with a new request parameter and check for the permission again. The button should be subtle.
