### ISSUE TITLE
No vote behaviour activation

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#33]
The "no vote" behaviour is currently not controlled by an ACP switch, there should be a way to disable this new behaviour.

Also, if you hit the "no vote" link, there is no way to vote later, and that might not be the desired situation.

And, if you do vote on a poll, and changes are allowed for that poll, it should be possible to remove the vote completely, not only change to a different value.

**Comment by Wolfsblvt** [comment]
Yes, you are right. An ACP switch is important for that.

I think it is correct that you can change to a vote if vote change is not allowed for this poll.
Can't you change to a vote if "allow vote change" is activated?

No. "Vote change" doesn't mean that you can remove votes. That isn't the case for phpBB default, and I don't want to add that.
"No vote" is just some sugar for lazy people that don't want to click "Show votes" all the time :P

**Comment by javiexin** [comment]
If "no vote" is sugar for lazy people, it should be possible to vote after you hit it, even if "vote change" is not active, and that is not the case.  With "vote change" active, I think the "no vote" has almost no effect, except some Ajax on first call (i think).

And we are changing default phpbb behavior all the time, so why not one more? :-)

**Comment by Wolfsblvt** [comment]
Why? If you chose not to vote, you have chosen what to do in this poll. So if no change is allowed, you should not be able to vote again.
And why does it have almost no effect with vote change active?

**Comment by javiexin** [comment]
Because the standard behavior of phpbb polls is that you can see the already submitted votes, and then decide your vote, and that is not possible now.  There is no way to say "I want to see current results and vote later", while this was possible before.

If "vote change" is active, behaviour is as follows: if you have not voted before, the message on "no vote" shows up, and if you click it, it displays results BUT you are NOT allowed to submit your vote after the AJAX refresh.  If you reload the page, then you can vote correctly, and the "no vote" message is not shown.  So, I think the problem is the AJAX refresh.  Otherwise, I think it is ok.

**Comment by Wolfsblvt** [comment]
Ah yeah, I think I remember, I haven't pushed the "S_CAN_CHANGE_VOTE" to javascript code.
But you are right, with both points.
Should be fixed. I will keep that issue open and do that later after everything of yours is done etc.

**Comment by javiexin** [comment]
Question/proposal: wouldn't it be better to store the "no vote" preference in a cookie rather than in the DB?  Reason is the creation of inconsistencies in the use of the DB, overloading the concept of "vote", and creating a special case of vote.  If the final intent of this is to create a "viewing preference" for the user, I think a cookie is a better mechanism.  Yes, it will not be preserved across devices/browsers, but again, as it is a "preference", it would not be too relevant.  What do you think?

**Comment by Wolfsblvt** [comment]
Hmh. I am not quite sure. I don't like the use of cookies for things you may want to have permanent.
If you don't want to vote in a poll, you surely don't want to vote in a week either. Or on your smartphone.
If you don't like the design with the bit "hacky" use of the votes table, I could create a new one in the database. I just thought that is not needed to store exact the same data that is already given in the votes table design.

**Comment by javiexin** [comment]
No, it is ok as is.  I just was proposing an alternative.  But let's leave it as it is.  Thanks.
