### ISSUE TITLE
Inconsistent messages when guest votes exist

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#34]
If a poll has guest votes, the messages that show with "Show poll voters" may be inconsistent.  For example, a poll may have a number of "guest" votes, and no registered voters, then the message will show as "Voters: None" and have a number of votes.  Similarly, if you vote on such a poll, the new message will show "Voters: None, user".

**Comment by Wolfsblvt** [comment]
Didn't know that guests can vote o.O
Yeah, should be fixed then.

**Comment by javiexin** [comment]
Yes, and the votes are only stored in cookies

**Comment by Wolfsblvt** [comment]
Cookies? So no other can see those votes?

**Comment by javiexin** [comment]
Guest votes are only accounted for in the "options" table as a total number, no trace of them in the "votes" table. The cookies are used to track the votes sent from an specific browser, but a guest may re-vote by clearing cookies or changing device or browser.
I always remove the permission to vote from guests, but some may want to allow it... So I guess we will have to fix this :(
