### ISSUE TITLE
Specify poll end date/time

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#37]
Currently, the only way to specify the poll duration is by a number of days since posting the poll.  This is not too granular, and limits the possibility to specify precisely when a poll ends, such as Midnight on Sunday, or so...
There should be a way to specify the poll end date/time in a more precise way, when publishing the poll.

**Comment by Wolfsblvt** [comment]
Sounds reasonable. Don't think an acp option for that is needed, this can be done with simply replacing the numerical box by some kind of datetime picker.

**Comment by javiexin** [comment]
Current solution includes acp switch, keeps the current input method, to allow for endless polls, and the datetime picker is very simple, and overrides poll length and start in case of entering both.

**Comment by Wolfsblvt** [comment]
Okay, ACP swith shouldn't hurt.

But why do you overwrite acp start? What could a reason be to change poll start? And if you change it to the future, will you not be able to vote?

**Comment by javiexin** [comment]
The way polls are computed internally (phpbb core) is by calculating the length of the poll in full days.  So, if you want to end the poll in, say, 5 hours, you have to make it look like you started the poll 19 hours ago, and lasts one day.
And if you are editing the poll, yes, you can reopen an already closed poll, or close an open poll.  This is no change from current behaviour.

**Comment by Wolfsblvt** [comment]
Sure? I thought the length of a poll is given in seconds, and phpBB uses days to calculate it. I can remember that I could modify end of a poll in my forum by setting poll length in the db manually to something fitting in seconds.
So no need to modify the start date. I think we should not touch the poll start date.

**Comment by javiexin** [comment]
True, length is stored in seconds in the db, but it is translated to days immediately after reading it by the core, and in extensions you only see days. So, there is no other option in an extension (in a mod we could do what you suggest, but not in 3.1)

**Comment by Wolfsblvt** [comment]
Okay, I understand.

**Comment by javiexin** [comment]
We could save (directly to the db, not through existing code) whatever poll length in seconds. But then, if you tried to edit the poll, data would not be correct... We would have to read the db again, and complicate code even more.

**Comment by javiexin** [comment]
Sorry, I was writing while you answered

**Comment by Wolfsblvt** [comment]
Nah, let's just keep it this way, that's okay.

**Comment by javiexin** [comment]
After all these changes, we should probably try to release a new version for external testing and possible suggestions of new functionality, before we close this extension.  What do you think?  Where do we put the cutoff for this version?

**Comment by Wolfsblvt** [comment]
We should probably chat about this again, soon.

**Comment by Wolfsblvt** [comment]
Isn't that one closed with #38?

**Comment by javiexin** [comment]
Yes, it is closed, except if any error come up.
