### ISSUE TITLE
Automatic notification if hidden poll you voted ended

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/advancedpolls#39]
Should be integrated with the phpBB notification system.

What do you think about that, @javiexin?

**Comment by javiexin** [comment]
Agreed.  If I have to code it, it will be my first notification :)

**Comment by Wolfsblvt** [comment]
If you want it to do, you could do it :P 
I would take it otherwise, shouldn't be a big problem.

I have to think about how the notification is sended though. Cron task would be over the top maybe, so we need some custom stuff that has a timestamp when the next notification needs to be executed or something. That's a bit more complicated.

**Comment by javiexin** [comment]
As I know nothing about notifications, it is probably better that you take it.  I can help if you need it, of course.

**Comment by Wolfsblvt** [comment]
I will take that, no problem. I will find a way for that.

**Comment by javiexin** [comment]
I have the code almost ready, final tests ongoing...  Will make a separate PR when ready.
With a cron task and a new notification!

**Comment by Wolfsblvt** [comment]
Great to hear that, thank you :D
