### ISSUE TITLE
Missing $message variable inside function

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/advancedpolls#44]
see https://scrutinizer-ci.com/g/Wolfsblvt/advancedpolls/issues/master/files/core/advancedpolls.php?selectedSeverities%5B0%5D=10&orderField=path&order=asc#inspectioncomment-781479450

**Comment by Wolfsblvt** [comment]
@javiexin: Can you take a look at this?

**Comment by javiexin** [comment]
I cannot access the above url... If/when I can, I will tell you, but if it is a but, yes, I will take it.

**Comment by Wolfsblvt** [comment]
Why can't you? Should work, I have tested it on another browser..
This is one point the Scrutinizer analysis has regognized.

![Screenshot](http://i.imgur.com/2qkeZBZ.png)

Probleme here is that you have if/elseif, but no else, so $message is not assigned if both are not hit. I don't know what you are doing there, so I would say you should take a look and see how the best way is to fix that.

**Comment by javiexin** [comment]
Not a problem.  It is an if a elseif b within another if a or b, so there is no else left :).
Anyhow, to catch this, I would just comment out the if part of the else if line.  That's all.

**Comment by Wolfsblvt** [comment]
Ah, I understand. I would use `$message = ''` above though, just in case if it will be extended somewhere in the future. The elseif check is correct there :D

**Comment by Wolfsblvt** [comment]
Closed by https://github.com/Wolfsblvt/advancedpolls/commit/2c61b53e1dff070db43ab49359674272e3e94872
