### ISSUE TITLE
Adjust permissions

### ISSUE THREAD

**Issue by javiexin** [Wolfsblvt/advancedpolls#52]
Permission u_see_voters is global, cannot be set by forum.  It should be possible to have this extra granularity.  So, we should remove u_see_voters permission, and replace it with local permission f_seevoters, make appropriate checks and changes to code, and register a new event to properly classify this permission as a "Forum/Poll" category permission.

**Comment by Wolfsblvt** [comment]
Do you want to do that?
And should that be done for the first testable version we will release, or later for the next one?

**Comment by javiexin** [comment]
Already done, PR on its way...  Simple change, and makes sense.
