### ISSUE TITLE
Move v1_2_1_configs.php to one of 1.2.0 ones

### ISSUE THREAD

**Issue by Wolfsblvt** [Wolfsblvt/advancedpolls#53]
https://github.com/Wolfsblvt/advancedpolls/blob/master/migrations/v1_2_1_configs.php
That should be integrated in 1.2.0 files.

@javiexin: We are not at 1.2.1 here. :P

So for us, we should deinstall and install the extension again. Too much migration files are bad.

**Comment by javiexin** [comment]
Ok.  As I have created the 1.2.2 file :-1: as part of the permission PR, I can do this as part of the same PR, or create yet another one. What do you prefer?

**Comment by Wolfsblvt** [comment]
Nah, you can do that in the same PR, that's just a very minor thing.
Just write "Closes xx" in the commit comment.

**Comment by javiexin** [comment]
Done.

**Comment by Wolfsblvt** [comment]
Great, thanks.
