### ISSUE TITLE
Relative date for expiring

### ISSUE THREAD

**Issue by Mauron** [Wolfsblvt/advancedpolls#70]
Hello,
I appreciate the _absolute_ expiring time implemented in Advanced polls, yet I think it would be handy to have it _relative_ instead, by adding a drop-down menu to specify if specified expiration number is 'days' or 'hours'.
Would it be harder to implement it that way?

Anyway, if you don't want (or can't) sort it that way, could you at least make faster to specify an absolute date/time, for example by adding the 'Today' link to autocompile year, month and day with current date and/or use some drop-down menus instead of number fields?

**Comment by javiexin** [comment]
Will look into it, however, I cannot commit now.  The main issue is that the way phpbb stores INTERNALLY the end time is as a number of days since poll publication.  What we have to do to specify end date/time is changing the start date/time to fix the number of days, so it is more complex than it looks.  Besides, you could eventually specify end date/time as delta in minutes or hours, BUT after that you could NOT change it this way, you could just use end date/time (the only reliable thing after initial setup, when you have changed the start date/time).

But, you may be lucky: if you ONLY specify one field in the end date/time, the others default to current date/time.

So, to specify 2 hours from now, just specify the hour, and set it to two hours after now.
I am (almost) positive this works as I explained here for date fields, but I am less sure about hour and minutes (may default to 0).  Please test and report back.

**Comment by Mauron** [comment]
Hi @javiexin,
I tried to test the absolute expire data field **by specifying only the day and the hour** and leaving blank year, month and minutes ones; the poll started and as expiring day was actually set today at the specifyed hour and '00' minutes.

That's quite good, yet if you didn't tell me about it I'd never think that I could ignore to specify some values there.

**Comment by javiexin** [comment]
Yes, we will have to add text to the _EXPLAIN language var.
Will look into the other possibilities as well.

**Comment by javiexin** [comment]
Ok, I have looked at this in more detail, and I have a better evaluation.
1) Given the positioning of the label (Days), we would need a new JS file and procedure to remove the label and replace it with a dropdown selector - not possible to do it with template events
2) If we added days and hours in the dropdown (maybe minutes, or weeks, but I don't think so), we would have to use a cumbersome mechanism to make up for full days (the only thing that may be stored in the phpbb db), giving a new start date as well.  In case the poll would have to be edited after, the value shown (for length) might be different than what was introduced, playing with hours, the topic publication date, the calculated poll start, current poll end and now.  So it might create some doubts.

Do you think it still makes sense?

**Comment by Mauron** [comment]
1) Can't you do it with available current events or can't you di it with events anyway?
You may require an event in the first case.
2) For now, let's keep focus on hours (for a week poll one can type down 7 days, you can't type 0.5 for a 12 hours poll though).
In short, a topic poll would have to be edited after publishing to tune expiration up?
I guess people won't go for that.

I guess we have to leave it as is for now, hoping that expiration time will be handled differently in phpBB 3.2; I was not aware of the limitation, sorry for pressuring you.

**Comment by javiexin** [comment]
1) Can't do it with events: events do not allow to "remove" or "replace" code (or text). That needs JS.
2) Ok, I will see if I can craft something with hours only.

By the way, poll editing is possible, and yet I agree it should not be done frequently, if it can be done, it should be done correctly.  Expiration may be tuned up, or down, may be added (an endless poll may be made to finish) or removed (a timed poll may be turned into endless)... everything is allowed.

**Comment by javiexin** [comment]
@Mauron Given that you do not care too much about editing a poll after being set, would you care if, regardless of the way the data is input, on editing, the default would always be "Days"?
That is, say you configure a poll to end in 30 hours.  That would work just fine.  If you later try to edit, the poll would show a poll length of 2 days (with an adjusted start, that you do not see, and an specific end, that you do see, that matches the originally specified of start+30 hours).  If you were to change the duration of the poll there, it would be better to do it adjusting the poll end, as poll length would be less clear (the start is not undefined, it is original_start+30-2*24 hours, but it is not visible either) and besides, the poll end data would be fully filled in (so you would just need to change whatever you want  to adjust, not everything).
If this is ok, I have the code ready to merge, so it would make it into 1.2.1, that I will release in a couple of days, with all the patches to the bugs found up to now.
What do you think?

**Comment by Mauron** [comment]
So you sorted out some trick about the stored poll start?
Well, I actually don't mind about editing a poll if I can actually specify a duration in hours, so if you feel confident about your solution I'm fine with it as long as I haven't to specify an absolute time and date for poll expire. :+1:

**Comment by javiexin** [comment]
Done, just wait for next rev
