### ISSUE TITLE
Some options of poll are reseted after when i edit the poll

### ISSUE THREAD

**Issue by Galixte** [Wolfsblvt/advancedpolls#91]
Hi @javiexin,

if i edit the poll, some options of the poll are reseted:
- Maximum votes:
- Total votes:
- Hide votes:
- Limit votes:
- Show poll voters:
- Show results ordered:

**Comment by javiexin** [comment]
Please, use phpbb forum for discussiono f potential bugs. When confirmed, then it is time to create the issuei n github

**Comment by Galixte** [comment]
Ok fine.

**Comment by javiexin** [comment]
Not confirmed, so until further information is available, this is closed as won't fix (not a bug).
